"""Stdlib only. Writes figures/derived_numbers.tex: Wilson intervals for Figure (references) and
numbers from run artifacts used in the text. Every value is computed, none typed."""
import re, json, math, sys
tex = open(sys.argv[1]).read()
out = ['% ===== begin figures/derived_numbers.tex =====', '% Generated by figscripts/gen_numbers.py. Do not edit by hand.']
def wilson(p, n, z=1.959964):
    d = 1 + z*z/n; c = (p + z*z/(2*n)) / d; h = z*math.sqrt(p*(1-p)/n + z*z/(4*n*n)) / d
    return max(0, c-h), min(1, c+h)

def fisher_exact_p(a, b, c, d):
    """Two-sided Fisher exact p for [[a, b], [c, d]] (sum of tables no more likely than the observed)."""
    from math import comb
    r1, c1, n = a + b, a + c, a + b + c + d
    pmf = lambda x: comb(c1, x) * comb(n - c1, r1 - x) / comb(n, r1)
    p0 = pmf(a)
    return sum(pmf(x) for x in range(max(0, r1 + c1 - n), min(r1, c1) + 1) if pmf(x) <= p0 * (1 + 1e-9))

N = 84
for name in ['bcRateStoSilentbreak','bcGenStoSilentbreak','bcRateStoDegradation','bcGenStoDegradation','bcRateStoRedirect','bcGenStoRedirect']:
    m = re.search(r'\\newcommand\{\\'+name+r'\}\{([^}]*)\}', tex)
    pts = re.findall(r'\((\d+),([\d.]+)\)', m.group(1))
    s = ' '.join(f'({k},{p}) += (0,{wilson(float(p),N)[1]-float(p):.3f}) -= (0,{float(p)-wilson(float(p),N)[0]:.3f})' for k, p in pts)
    out.append(f'\\newcommand{{\\{name}CI}}{{{s}}}')
# exploratory GPT-4o run (runs/2026-09-12_gpt4o_twoturn_k10/summary.json)
ex = json.load(open(sys.argv[2]))
sb, nc = ex['silent_break'], ex['no_change']
c = sb['cells']; a, b, cc, dd = c['(1, 1)'], c['(1, 0)'], c['(0, 1)'], c['(0, 0)']
OR = ((a+.5)*(dd+.5))/((b+.5)*(cc+.5)); se = math.sqrt(sum(1/(x+.5) for x in (a, b, cc, dd)))
vals = dict(exN=sb['n'], exSBDet=sb['detection'], exSBLoc=sb['localization'], exNCFalse=nc['n']-nc['detection'],
            exNCRouteOpt=nc['route_optimal'], exCellLocOpt=a, exCellLocOnly=b, exCellOptOnly=cc, exCellNeither=dd,
            exOR=f'{OR:.2f}', exORlo=f'{math.exp(math.log(OR)-1.96*se):.2f}', exORhi=f'{math.exp(math.log(OR)+1.96*se):.2f}',
            exFisherP=f'{fisher_exact_p(a,b,cc,dd):.2f}')
for k, v in vals.items(): out.append(f'\\newcommand{{\\{k}}}{{{v}}}')
# evidence-network neighbour shares (figscripts/make_figures.py -> figure_summary.json)
fs = json.load(open(sys.argv[3]))
for key, tag in (('rate', 'Rate'), ('transition', 'Trans')):
    r = fs['redirect_neighbours_K10'][key]
    out.append(f'\\newcommand{{\\redirNbNoChange{tag}}}{{{round(100*r["no_change"])}}}')
    out.append(f'\\newcommand{{\\redirNbBreak{tag}}}{{{round(100*(r["silent_break"]+r["irrelevant"]))}}}')
out.append('% ===== end figures/derived_numbers.tex =====')
open(sys.argv[4] if len(sys.argv) > 4 else 'figures/derived_numbers.tex', 'w').write('\n'.join(out) + '\n'); print('\n'.join(out[-8:]))
