"""Write every offline reference number into ECPM_main.tex from the result files, so no printed
reference value is typed by hand. Sources: runs/references/summary.json (check_references.py, 8 nodes)
and runs/references/offline_numbers.json (experiments/offline_numbers.py). Prints each value that
changed. Usage: python3 paper/fill_offline.py TEX"""
import json, os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
p = sys.argv[1]; t = open(p).read()
agg = json.load(open(os.path.join(ROOT, "runs/references/summary.json")))["aggregate"]["cells"]
off = json.load(open(os.path.join(ROOT, "runs/references/offline_numbers.json")))
cal8 = {**off["1_calibration_detection_n8"]}
s16 = off["3_sixteen_nodes"]
COND = {"Silentbreak": "silent_break", "Degradation": "degradation", "Redirect": "redirect",
        "Irrelevant": "irrelevant", "Hardremoval": "hard_removal"}
REF = {"Rate": "rate", "Trans": "transition", "Bayes": "bayes"}
changed = []
def setmacro(name, value):
    global t
    pat = r"\\newcommand\{\\" + name + r"\}\{[^}]*\}"
    m = re.findall(pat, t); assert len(m) == 1, (name, len(m))
    new = "\\newcommand{\\" + name + "}{" + value + "}"
    if m[0] != new: changed.append(f"{name}: {m[0].split('}{',1)[1][:-1]} -> {value}")
    t = t.replace(m[0], new)
# Localization curves, 8 nodes and 16 nodes
for name in re.findall(r"\\newcommand\{\\(bc(?:Sixteen)?(?:Rate|Trans|Bayes)(?:Sto|Det)\w+?)\}", t):
    if name.endswith("CI"): continue
    m = re.match(r"bc(Sixteen)?(Rate|Trans|Bayes)(Sto|Det)(\w+)$", name)
    six, ref, mode, cond = m.groups(); mode = mode.lower(); cond = COND[cond]; pts = []
    for k in (5, 10, 20):
        if six:
            v = s16["curves"][f"{REF[ref]}|{mode}|{cond}|{k}"]
        else:
            c = agg[f"{mode}|{cond}|{k}"]; v = f'{c["loc_" + REF[ref]] / c["n"]:.2f}'
        pts.append(f"({k},{v})")
    setmacro(name, " ".join(pts))
setmacro("pctBayesDetSB", f'{cal8["bayes|sto|10"]["SB"]:.1f}')
setmacro("pctRateDetSB", f'{cal8["rate|sto|10"]["SB"]:.1f}')
# Calibration tables: rebuild every reference row
def row(label, cal, ref):
    cells = []
    for k in (5, 10, 20):
        c = cal[f"{ref}|sto|{k}"]; cells += [f'{c["FA"]:.1f}', f'{c["SB"]:.1f}', f'{c["Deg"]:.1f}']
    return f"{label} & " + " & ".join(cells) + " \\\\"
for lab, cal in (("tab:calibration}", cal8), ("tab:calibration16}", s16["calibration"])):
    s = t.index("\\label{" + lab); e = t.index("\\end{tabular}", s); blk = t[s:e]
    for label, ref in (("Rate counter", "rate"), ("Transition counter", "transition"), ("Bayesian observer", "bayes")):
        old = re.findall(r"^" + label + r" &.*\\\\$", blk, flags=re.M); assert len(old) == 1, (lab, label)
        new = row(label, cal, ref)
        if old[0] != new: changed.append(f"{lab} {label}: {old[0]} -> {new}")
        blk = blk.replace(old[0], new)
    t = t[:s] + blk + t[e:]
# Detection table: Bayes cells (offline slots)
for mode, M in (("sto", "Stoch."), ("det", "Det.")):
    c = cal8[f"bayes|{mode}|10"]
    a = re.search(r"\n" + re.escape(M) + r" & (?:[\d.]+ & ){6}(\\PH & \\PH & \\PH)", t)
    if not a: continue  # already filled
    s, e = a.span(1); t = t[:s] + f'{c["sens"]:.2f} & {c["spec"]:.2f} & {c["dprime"]:.2f}' + t[e:]
    changed.append(f"tab:detection {M} Bayes: {c['sens']:.2f}/{c['spec']:.2f}/{c['dprime']:.2f} (new)")
# Sixteen-node table: Bayes silent break
a = "Stoch. & Silent break & 0.95 & \\PH & 1.00 & 0.79"
if a in t: t = t.replace(a, a.replace("\\PH", s16["curves"]["bayes|sto|silent_break|10"])); changed.append("tab:n16 Bayes SB (new)")
# Evidence-only reference agent: adaptation lag (median over runs where the broken link was tried)
lag = off["5_reference_agent_lag"]
anchor = "% ===== end figures/ref_k10.tex ====="
blk = (f"% ===== begin figures/reference_agent.tex =====\n% Generated by paper/fill_offline.py from runs/references/offline_numbers.json. Do not edit by hand.\n"
       f"\\newcommand{{\\lagRefAgent}}{{{lag['median']:g}}}\n\\newcommand{{\\nLagRefAgent}}{{{lag['n_with_failure']}}}\n\\newcommand{{\\nLagRefSeeds}}{{{lag['seeds']}}}\n"
       f"% ===== end figures/reference_agent.tex =====")
if "\\newcommand{\\lagRefAgent}" not in t:
    t = t.replace(anchor, anchor + "\n" + blk)
for a, b in (("against \\PH{} for the evidence-only reference agent", "against a median of \\lagRefAgent{} for the evidence-only reference agent (\\nLagRefAgent{} of \\nLagRefSeeds{} seeds, where it tried the broken link)"),
             ("against \\RES{} for the reference agent.", "against a median of \\lagRefAgent{} for the reference agent.")):
    t = t.replace(a, b)
# Transcribed numbers: keep only what a script reproduces
tr = off["6_transcribed"]
setmacro("pctOldFalseAlarm", str(tr["pctOldFalseAlarm"]["value"]))
for a, b in (("a halved off-route link was found on only \\pctHalvedLo{} to \\pctHalvedHi{} percent of seeds at $K = 10$",
              "a halved off-route link is not reliably localized at $K = 10$"),
             ("yet after the broken link first failed it kept choosing it on \\pilotRepeatPct{} percent of its later visits to that node, with an adaptation lag of \\pilotLag{} steps.",
              "yet after the broken link first failed it kept choosing it on later visits to that node.")):
    t = t.replace(a, b)
for m in ("pilotRepeatPct", "pilotLag", "pctHalvedLo", "pctHalvedHi"):
    t = re.sub(r"\\newcommand\{\\" + m + r"\}\{[^}]*\}\n", "", t)
if "pctOldFalseAlarm is regenerated" not in t: t = t.replace("% ===== begin figures/transcribed_numbers.tex =====", "% ===== begin figures/transcribed_numbers.tex =====\n% pctOldFalseAlarm is regenerated by paper/fill_offline.py (runs/baseline_k_sweep_seeds1-30.json).")
t = t.replace("UNVERIFIED: transcribed from earlier drafts", "verified by paper/fill_offline.py")
open(p, "w").write(t)
print("\n".join(changed)); print(f"{len(changed)} values written; \\PH left: {t.count(chr(92)+'PH')-2}")

# Queried pairs restricted (experiments/queried_restricted.py -> runs/references/queried_restricted.json)
t = open(p).read()
q = json.load(open(os.path.join(ROOT, "runs/references/queried_restricted.json")))
g = q["localization_given_target_queried"]
blk = ("% ===== begin figures/queried_restricted.tex =====\n% Generated by paper/fill_offline.py from runs/references/queried_restricted.json. Do not edit by hand.\n"
       f"\\newcommand{{\\nQueriedTarget}}{{{q['n_target_queried']}}}\n\\newcommand{{\\nQueriedSeeds}}{{{q['n']}}}\n"
       f"\\newcommand{{\\qrRate}}{{{g['rate']:.2f}}}\n\\newcommand{{\\qrBayes}}{{{g['bayes']:.2f}}}\n\\newcommand{{\\qrGen}}{{{g['generator']:.2f}}}\n"
       "% ===== end figures/queried_restricted.tex =====")
if "\\newcommand{\\nQueriedTarget}" not in t:
    a = "% ===== end figures/ref_k10.tex ====="; t = t.replace(a, a + "\n" + blk)
a = "Restricted to the queried pairs, the references localize \\PH{} of silent breaks."
if a in t:
    t = t.replace(a, "The target is among the queried pairs on \\nQueriedTarget{} of the \\nQueriedSeeds{} seeds. On those seeds, restricted to the queried pairs, the references localize between \\qrRate{} (rate counter) and \\qrGen{} (generator-aware observer) of silent breaks at $K = 10$.")
a = "decided by seed alone so that every condition of a seed sees the same set."
if a in t:
    t = t.replace(a, "decided by seed alone so that every condition of a seed sees the same set, except that under irrelevant the irrelevant link takes the target's place.")
open(p, "w").write(t); print("queried-pairs slot filled; \\PH left:", t.count(chr(92) + "PH") - 2)
