"""Write the coordinate macros for the reference figure (fig:refs) into ECPM_main.tex, between
'% ===== begin figures/ref_k10.tex' and '% ===== end figures/ref_k10.tex' (inserted once if absent).
Source: runs/references/part_sto_10.json from experiments/reference_sweep.py. Stdlib only.
Usage: python3 paper/make_fig_refs.py TEX"""
import json, math, os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import resource_mdp as R
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rows = json.load(open(os.path.join(ROOT, "runs/references/part_sto_10.json")))["rows"]
by = {}
for r in rows:
    if r["condition"] != "no_change": by.setdefault(r["seed"], set()).add(r["condition"])
el = {s for s, c in by.items() if len(c) == 5}
rows = [r for r in rows if r["seed"] in el]
def moved(seed):
    i = R.make_pair(seed, "degradation", deterministic=False, matched=True)
    return i.m0.optimal_route(i.start)[0] != i.m1.optimal_route(i.start)[0]
deg = [r for r in rows if r["condition"] == "degradation"]
mv = {r["seed"] for r in deg if moved(r["seed"])}
groups = [("irrelevant", [r for r in rows if r["condition"] == "irrelevant"]),
          ("silent_break", [r for r in rows if r["condition"] == "silent_break"]),
          ("hard_removal", [r for r in rows if r["condition"] == "hard_removal"]),
          ("redirect", [r for r in rows if r["condition"] == "redirect"]),
          ("deg_moves", [r for r in deg if r["seed"] in mv]),
          ("deg_restraint", [r for r in deg if r["seed"] not in mv])]
assert [len(g) for _, g in groups] == [84, 84, 84, 84, 60, 24], [len(g) for _, g in groups]
def wilson(k, n, z=1.959964):
    p = k / n; d = 1 + z * z / n; c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return p, max(0.0, c - h), min(1.0, c + h)
REFS = [("Rate", "rate", -0.24), ("Trans", "transition", -0.08), ("Bayes", "bayes", 0.08), ("Gen", "generator", 0.24)]
out = ["% ===== begin figures/ref_k10.tex =====",
       "% Generated by paper/make_fig_refs.py from runs/references/part_sto_10.json. Do not edit by hand.",
       "% Rows (y): 6 irrelevant, 5 silent break, 4 hard removal, 3 redirect, 2 degradation (route moves), 1 degradation (restraint)."]
for tag, key, off in REFS:
    pts = []
    for i, (_, g) in enumerate(groups):
        k = sum(r[key]["loc"] == r["truth"] for r in g); p, lo, hi = wilson(k, len(g))
        pts.append(f"({p:.3f},{6 - i + off:.2f}) += ({max(0.0, hi - p):.3f},0) -= ({max(0.0, p - lo):.3f},0)")
    out.append(f"\\newcommand{{\\figRef{tag}}}{{{' '.join(pts)}}}")
out.append("% ===== end figures/ref_k10.tex =====")
block = "\n".join(out)
p = sys.argv[1]; t = open(p).read()
b, e = "% ===== begin figures/ref_k10.tex =====", "% ===== end figures/ref_k10.tex ====="
if t.count(b) == 1:
    s = t.index(b); t = t[:s] + block + t[t.index(e) + len(e):]
else:
    anchor = "% ===== end figures/derived_numbers.tex ====="
    assert t.count(anchor) == 1, anchor
    t = t.replace(anchor, anchor + "\n" + block)
open(p, "w").write(t); print(block)
